# Generated by Django 3.1.3 on 2020-11-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='bio',
            field=models.TextField(),
        ),
    ]
